cloud:
  aws:
    region:
      static: eu-west-1
    credentials:
      profile-name: default
      access-key: foo
      secret-key: bar
    sqs:
      endpoint: http://localhost:4566
      region: ${cloud.aws.region.static}